<?php
$server="mysql17.000webhost.com"; 
$database="a4744940_app";
$dbpass="@toor.";
$dbuser="a4744940_root";
$link=mysql_connect("mysql17.000webhost.com","a4744940_root","@toor.");
mysql_select_db("a4744940_app",$link);
/*$server="localhost"; 
$database="root";
$dbpass="toor";
$dbuser="qcompras";
$link=mysql_connect("localhost","root","toor");
mysql_select_db("qcompras",$link);*/
?>